/** Demo fixture — Lakeview Ethanol maintenance actions (CMMS calibration / inspection / PM tracking) */

export type MaintenanceStatus = "Due" | "Overdue" | "Compliant";

export type MaintenanceRisk = "low" | "medium" | "high" | "critical";

export type MaintenanceActionCategory =
  | "Calibration"
  | "Inspection"
  | "Preventive Maintenance"
  | "Safety"
  | "Service";

export type MaintenanceWorkOrderStatus =
  | "Not started"
  | "Open"
  | "In progress"
  | "On hold"
  | "Closed";

export type MaintenanceAction = {
  id: string;
  itemId: string;
  itemName: string;
  category: MaintenanceActionCategory;
  plantId: "PLY" | "TRE";
  area: string;
  assetId: string;
  assetName: string;
  maintenanceType: string;
  status: MaintenanceStatus;
  criticality: MaintenanceRisk;
  riskLevel: MaintenanceRisk;
  dueDate: string;
  lastCompletedDate: string;
  nextScheduledDate: string;
  frequency: string;
  responsibleTeam: string;
  owner: string;
  workOrderId?: string;
  workOrderStatus: MaintenanceWorkOrderStatus;
  requiredParts: string;
  requiredPartsAvailable: boolean;
  storageLocation: string;
  estimatedDowntimeImpact: string;
  operationalImpact: string;
  recommendedAction: string;
  complianceImpact: string;
  sourceSystem: string;
  sourceRecordId: string;
  lastUpdatedAt: string;
};

/** Demo "today" anchor so Due-this-week logic is deterministic against the fixture dates */
export const MAINTENANCE_REFERENCE_TODAY = "2026-06-15";

export function daysUntilDue(
  dueDate: string,
  today: string = MAINTENANCE_REFERENCE_TODAY,
): number {
  const due = new Date(`${dueDate}T00:00:00`).getTime();
  const ref = new Date(`${today}T00:00:00`).getTime();
  return Math.round((due - ref) / (24 * 60 * 60 * 1000));
}

export const LAKEVIEW_MAINTENANCE_ACTIONS: MaintenanceAction[] = [
  {
    id: "mnt-1",
    itemId: "MNT-CAL-001",
    itemName: "Fermentation Tank Temperature Probe Calibration",
    category: "Calibration",
    plantId: "PLY",
    area: "Fermentation",
    assetId: "TT-6418-B",
    assetName: "Fermenter B Temperature Probe",
    maintenanceType: "6-month instrument calibration",
    status: "Due",
    criticality: "high",
    riskLevel: "medium",
    dueDate: "2026-06-18",
    lastCompletedDate: "2025-12-12",
    nextScheduledDate: "2026-06-18",
    frequency: "Every 6 months",
    responsibleTeam: "Instrumentation",
    owner: "James Reed",
    workOrderId: "WO-89001",
    workOrderStatus: "Open",
    requiredParts: "RTD thermowell seal kit",
    requiredPartsAvailable: true,
    storageLocation: "Instrument crib / Shelf 3",
    estimatedDowntimeImpact: "No downtime — online loop check",
    operationalImpact: "Temperature control accuracy on Ferm B batches",
    recommendedAction: "Schedule calibration before next batch drop",
    complianceImpact: "Quality system instrument accuracy record",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-CAL-6418B",
    lastUpdatedAt: "2026-06-15T09:30:00Z",
  },
  {
    id: "mnt-2",
    itemId: "MNT-CAL-002",
    itemName: "Fermentation Tank pH Probe Calibration",
    category: "Calibration",
    plantId: "PLY",
    area: "Fermentation",
    assetId: "AT-FERM-B",
    assetName: "Fermenter B pH Analyzer",
    maintenanceType: "Buffer 2-point calibration",
    status: "Due",
    criticality: "medium",
    riskLevel: "medium",
    dueDate: "2026-06-20",
    lastCompletedDate: "2026-03-20",
    nextScheduledDate: "2026-06-20",
    frequency: "Quarterly",
    responsibleTeam: "QA / Lab",
    owner: "QA / Lab",
    workOrderId: "WO-89002",
    workOrderStatus: "Open",
    requiredParts: "pH buffer 4.0 / 7.0, KCl electrolyte",
    requiredPartsAvailable: true,
    storageLocation: "Lab reagent cabinet",
    estimatedDowntimeImpact: "No downtime",
    operationalImpact: "pH-driven dosing decisions on fermentation",
    recommendedAction: "Calibrate with fresh buffers",
    complianceImpact: "Lab method accuracy record",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-CAL-FERMB-PH",
    lastUpdatedAt: "2026-06-15T09:00:00Z",
  },
  {
    id: "mnt-3",
    itemId: "MNT-INS-001",
    itemName: "Beer Feed Pump Mechanical Seal Inspection",
    category: "Inspection",
    plantId: "TRE",
    area: "Distillation",
    assetId: "P-4402",
    assetName: "Beer Feed Pump",
    maintenanceType: "Mechanical seal condition inspection",
    status: "Overdue",
    criticality: "high",
    riskLevel: "high",
    dueDate: "2026-06-08",
    lastCompletedDate: "2026-03-08",
    nextScheduledDate: "2026-06-08",
    frequency: "Quarterly",
    responsibleTeam: "Reliability",
    owner: "Maintenance Planner",
    workOrderId: "WO-88721",
    workOrderStatus: "On hold",
    requiredParts: "Centrifugal pump mechanical seal kit",
    requiredPartsAvailable: false,
    storageLocation: "Warehouse A / Bin 14-C",
    estimatedDowntimeImpact: "4-6 h if seal change required",
    operationalImpact: "Distillation beer feed reliability",
    recommendedAction: "Expedite seal kit, then complete inspection",
    complianceImpact: "None — reliability driven",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-P4402",
    lastUpdatedAt: "2026-06-15T08:45:00Z",
  },
  {
    id: "mnt-4",
    itemId: "MNT-INS-002",
    itemName: "Centrifuge Vibration Inspection",
    category: "Inspection",
    plantId: "PLY",
    area: "Oil Recovery",
    assetId: "CF-2201",
    assetName: "Whole Stillage Centrifuge",
    maintenanceType: "Vibration route reading",
    status: "Due",
    criticality: "medium",
    riskLevel: "medium",
    dueDate: "2026-06-21",
    lastCompletedDate: "2026-05-21",
    nextScheduledDate: "2026-06-21",
    frequency: "Monthly",
    responsibleTeam: "Reliability",
    owner: "Reliability",
    workOrderStatus: "Not started",
    requiredParts: "None",
    requiredPartsAvailable: true,
    storageLocation: "N/A",
    estimatedDowntimeImpact: "No downtime — online reading",
    operationalImpact: "Corn oil recovery throughput",
    recommendedAction: "Take route readings and trend",
    complianceImpact: "None",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-CF2201",
    lastUpdatedAt: "2026-06-15T07:50:00Z",
  },
  {
    id: "mnt-5",
    itemId: "MNT-CAL-003",
    itemName: "Distillation Column Pressure Transmitter Calibration",
    category: "Calibration",
    plantId: "TRE",
    area: "Distillation",
    assetId: "PT-3015",
    assetName: "Rectifier Column Pressure Transmitter",
    maintenanceType: "Annual pressure calibration",
    status: "Overdue",
    criticality: "high",
    riskLevel: "high",
    dueDate: "2026-06-05",
    lastCompletedDate: "2025-06-05",
    nextScheduledDate: "2026-06-05",
    frequency: "Annual",
    responsibleTeam: "Instrumentation",
    owner: "James Reed",
    workOrderId: "WO-88950",
    workOrderStatus: "Open",
    requiredParts: "Calibration reference standard",
    requiredPartsAvailable: true,
    storageLocation: "Instrument crib / Shelf 1",
    estimatedDowntimeImpact: "Possible column hold during cal",
    operationalImpact: "Column pressure control and safety interlock input",
    recommendedAction: "Calibrate at next column slowdown",
    complianceImpact: "PSM-related instrument record",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-CAL-PT3015",
    lastUpdatedAt: "2026-06-15T08:10:00Z",
  },
  {
    id: "mnt-6",
    itemId: "MNT-SAF-001",
    itemName: "Boiler Safety Valve Inspection",
    category: "Safety",
    plantId: "TRE",
    area: "Utilities",
    assetId: "PSV-BLR-01",
    assetName: "Boiler Main Safety Relief Valve",
    maintenanceType: "ASME relief valve pop test",
    status: "Overdue",
    criticality: "critical",
    riskLevel: "critical",
    dueDate: "2026-05-30",
    lastCompletedDate: "2025-05-30",
    nextScheduledDate: "2026-05-30",
    frequency: "Annual",
    responsibleTeam: "Reliability",
    owner: "Brian Henderson",
    workOrderId: "WO-88880",
    workOrderStatus: "Open",
    requiredParts: "Certified test bench / valve gag",
    requiredPartsAvailable: true,
    storageLocation: "Safety cage / Locker S2",
    estimatedDowntimeImpact: "Boiler outage during bench test",
    operationalImpact: "Steam supply protection — plant-wide impact",
    recommendedAction: "Schedule valve pull and bench test urgently",
    complianceImpact: "ASME / state boiler code certification",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-SAF-BLR01",
    lastUpdatedAt: "2026-06-15T09:15:00Z",
  },
  {
    id: "mnt-7",
    itemId: "MNT-INS-003",
    itemName: "Cooling Tower Fan Motor Inspection",
    category: "Inspection",
    plantId: "TRE",
    area: "Utilities",
    assetId: "CT-FAN-02",
    assetName: "Cooling Tower Cell 2 Fan Motor",
    maintenanceType: "Motor & gearbox inspection",
    status: "Compliant",
    criticality: "medium",
    riskLevel: "low",
    dueDate: "2026-08-10",
    lastCompletedDate: "2026-02-10",
    nextScheduledDate: "2026-08-10",
    frequency: "Semi-annual",
    responsibleTeam: "Electrical maint.",
    owner: "Electrical maint.",
    workOrderStatus: "Closed",
    requiredParts: "None",
    requiredPartsAvailable: true,
    storageLocation: "N/A",
    estimatedDowntimeImpact: "Single cell only — redundant",
    operationalImpact: "Cooling capacity margin",
    recommendedAction: "On schedule — no action",
    complianceImpact: "None",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-CTFAN02",
    lastUpdatedAt: "2026-06-13T16:00:00Z",
  },
  {
    id: "mnt-8",
    itemId: "MNT-PM-001",
    itemName: "CIP Pump Preventive Maintenance",
    category: "Preventive Maintenance",
    plantId: "PLY",
    area: "Utilities",
    assetId: "P-CIP-01",
    assetName: "CIP Supply Pump",
    maintenanceType: "Quarterly PM service",
    status: "Due",
    criticality: "medium",
    riskLevel: "medium",
    dueDate: "2026-06-19",
    lastCompletedDate: "2026-03-19",
    nextScheduledDate: "2026-06-19",
    frequency: "Quarterly",
    responsibleTeam: "Utilities maint.",
    owner: "Utilities maint.",
    workOrderId: "WO-89010",
    workOrderStatus: "Open",
    requiredParts: "PM kit (gaskets, lubricant)",
    requiredPartsAvailable: true,
    storageLocation: "CIP storeroom",
    estimatedDowntimeImpact: "Brief CIP window pause",
    operationalImpact: "Cleaning cycle reliability",
    recommendedAction: "Complete PM during next CIP gap",
    complianceImpact: "Sanitation program record",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-PM-PCIP01",
    lastUpdatedAt: "2026-06-15T07:30:00Z",
  },
  {
    id: "mnt-9",
    itemId: "MNT-INS-004",
    itemName: "Ethanol Storage Tank Inspection",
    category: "Inspection",
    plantId: "PLY",
    area: "Loadout",
    assetId: "TK-200PF",
    assetName: "200-Proof Ethanol Storage Tank",
    maintenanceType: "API 653 in-service inspection",
    status: "Compliant",
    criticality: "high",
    riskLevel: "high",
    dueDate: "2026-09-01",
    lastCompletedDate: "2025-09-01",
    nextScheduledDate: "2026-09-01",
    frequency: "Annual external",
    responsibleTeam: "Reliability",
    owner: "Brian Henderson",
    workOrderStatus: "Closed",
    requiredParts: "None",
    requiredPartsAvailable: true,
    storageLocation: "N/A",
    estimatedDowntimeImpact: "None for external exam",
    operationalImpact: "Product storage integrity and containment",
    recommendedAction: "On schedule — next external Sep",
    complianceImpact: "API 653 / SPCC containment compliance",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-TK200PF",
    lastUpdatedAt: "2026-06-12T14:00:00Z",
  },
  {
    id: "mnt-10",
    itemId: "MNT-INS-005",
    itemName: "Denaturant Pump Inspection",
    category: "Inspection",
    plantId: "PLY",
    area: "Loadout",
    assetId: "P-DEN-01",
    assetName: "Denaturant Metering Pump",
    maintenanceType: "Metering accuracy + leak inspection",
    status: "Due",
    criticality: "medium",
    riskLevel: "medium",
    dueDate: "2026-06-22",
    lastCompletedDate: "2026-03-22",
    nextScheduledDate: "2026-06-22",
    frequency: "Quarterly",
    responsibleTeam: "Maintenance",
    owner: "Maintenance Planner",
    workOrderStatus: "Not started",
    requiredParts: "Diaphragm kit (spare on hand)",
    requiredPartsAvailable: true,
    storageLocation: "Warehouse A / Bin 09-B",
    estimatedDowntimeImpact: "Loadout pause if rebuild needed",
    operationalImpact: "Denaturant dosing accuracy for shipment certification",
    recommendedAction: "Verify metering accuracy",
    complianceImpact: "TTB denaturing accuracy record",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-PDEN01",
    lastUpdatedAt: "2026-06-15T08:05:00Z",
  },
  {
    id: "mnt-11",
    itemId: "MNT-INS-006",
    itemName: "CO2 Scrubber Inspection",
    category: "Inspection",
    plantId: "PLY",
    area: "Fermentation",
    assetId: "SCR-CO2-01",
    assetName: "CO2 Scrubber Column",
    maintenanceType: "Packing & spray nozzle inspection",
    status: "Compliant",
    criticality: "medium",
    riskLevel: "medium",
    dueDate: "2026-07-30",
    lastCompletedDate: "2026-01-30",
    nextScheduledDate: "2026-07-30",
    frequency: "Semi-annual",
    responsibleTeam: "Maintenance",
    owner: "Maintenance",
    workOrderStatus: "Closed",
    requiredParts: "None",
    requiredPartsAvailable: true,
    storageLocation: "N/A",
    estimatedDowntimeImpact: "None",
    operationalImpact: "CO2 emissions capture efficiency",
    recommendedAction: "On schedule",
    complianceImpact: "Air permit emissions control",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-SCRCO201",
    lastUpdatedAt: "2026-06-11T10:00:00Z",
  },
  {
    id: "mnt-12",
    itemId: "MNT-INS-007",
    itemName: "Grain Hammer Mill Bearing Inspection",
    category: "Inspection",
    plantId: "PLY",
    area: "Grain Handling",
    assetId: "HM-101",
    assetName: "Hammer Mill #1",
    maintenanceType: "Bearing temperature & wear inspection",
    status: "Overdue",
    criticality: "high",
    riskLevel: "high",
    dueDate: "2026-06-10",
    lastCompletedDate: "2026-04-10",
    nextScheduledDate: "2026-06-10",
    frequency: "Bi-monthly",
    responsibleTeam: "Reliability",
    owner: "Maintenance Planner",
    workOrderId: "WO-88990",
    workOrderStatus: "On hold",
    requiredParts: "Hammer mill bearing set",
    requiredPartsAvailable: false,
    storageLocation: "Warehouse A / Bin 21-A",
    estimatedDowntimeImpact: "Grind line outage if bearing fails",
    operationalImpact: "Front-end grind capacity feeds slurry",
    recommendedAction: "Source bearing set, then inspect/replace",
    complianceImpact: "None",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-HM101",
    lastUpdatedAt: "2026-06-15T08:30:00Z",
  },
  {
    id: "mnt-13",
    itemId: "MNT-INS-008",
    itemName: "Conveyor Belt Inspection",
    category: "Inspection",
    plantId: "PLY",
    area: "Grain Handling",
    assetId: "CV-105",
    assetName: "Grain Receiving Conveyor",
    maintenanceType: "Belt tracking & wear inspection",
    status: "Compliant",
    criticality: "low",
    riskLevel: "low",
    dueDate: "2026-08-05",
    lastCompletedDate: "2026-05-05",
    nextScheduledDate: "2026-08-05",
    frequency: "Quarterly",
    responsibleTeam: "Maintenance",
    owner: "Maintenance",
    workOrderStatus: "Closed",
    requiredParts: "None",
    requiredPartsAvailable: true,
    storageLocation: "N/A",
    estimatedDowntimeImpact: "Low — redundant receiving path",
    operationalImpact: "Grain receiving throughput",
    recommendedAction: "On schedule",
    complianceImpact: "None",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-CV105",
    lastUpdatedAt: "2026-06-10T12:00:00Z",
  },
  {
    id: "mnt-14",
    itemId: "MNT-CAL-004",
    itemName: "DDGS Dryer Temperature Sensor Calibration",
    category: "Calibration",
    plantId: "PLY",
    area: "DDGS",
    assetId: "TE-DRY-01",
    assetName: "DDGS Dryer Outlet Temperature Sensor",
    maintenanceType: "Temperature sensor calibration",
    status: "Due",
    criticality: "high",
    riskLevel: "medium",
    dueDate: "2026-06-17",
    lastCompletedDate: "2025-12-17",
    nextScheduledDate: "2026-06-17",
    frequency: "Every 6 months",
    responsibleTeam: "Instrumentation",
    owner: "James Reed",
    workOrderId: "WO-89015",
    workOrderStatus: "Open",
    requiredParts: "Reference thermocouple",
    requiredPartsAvailable: true,
    storageLocation: "Instrument crib / Shelf 2",
    estimatedDowntimeImpact: "No downtime",
    operationalImpact: "Dryer fire-risk control and DDGS quality",
    recommendedAction: "Calibrate — high-temp safety relevance",
    complianceImpact: "Fire prevention / NFPA dryer control",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-CAL-TEDRY01",
    lastUpdatedAt: "2026-06-15T07:40:00Z",
  },
  {
    id: "mnt-15",
    itemId: "MNT-CAL-005",
    itemName: "Wastewater pH Probe Calibration",
    category: "Calibration",
    plantId: "TRE",
    area: "Water Treatment",
    assetId: "AT-WW-01",
    assetName: "Effluent pH Analyzer",
    maintenanceType: "Buffer 2-point calibration",
    status: "Overdue",
    criticality: "medium",
    riskLevel: "medium",
    dueDate: "2026-06-09",
    lastCompletedDate: "2026-03-09",
    nextScheduledDate: "2026-06-09",
    frequency: "Quarterly",
    responsibleTeam: "Water Treatment",
    owner: "Utilities maint.",
    workOrderId: "WO-88975",
    workOrderStatus: "Open",
    requiredParts: "pH buffers, electrolyte",
    requiredPartsAvailable: true,
    storageLocation: "WWT control room",
    estimatedDowntimeImpact: "No downtime",
    operationalImpact: "Discharge pH monitoring accuracy",
    recommendedAction: "Calibrate to maintain permit accuracy",
    complianceImpact: "NPDES discharge permit monitoring",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-CAL-ATWW01",
    lastUpdatedAt: "2026-06-15T08:20:00Z",
  },
  {
    id: "mnt-16",
    itemId: "MNT-SVC-001",
    itemName: "Air Compressor Service",
    category: "Service",
    plantId: "PLY",
    area: "Utilities",
    assetId: "AC-700",
    assetName: "Plant Instrument Air Compressor",
    maintenanceType: "Vendor service (filters, oil)",
    status: "Compliant",
    criticality: "medium",
    riskLevel: "low",
    dueDate: "2026-07-20",
    lastCompletedDate: "2026-01-20",
    nextScheduledDate: "2026-07-20",
    frequency: "Semi-annual",
    responsibleTeam: "Utilities maint.",
    owner: "Utilities maint.",
    workOrderStatus: "Closed",
    requiredParts: "Service kit (vendor supplied)",
    requiredPartsAvailable: true,
    storageLocation: "Vendor managed",
    estimatedDowntimeImpact: "Backup compressor covers",
    operationalImpact: "Instrument air for controls and valves",
    recommendedAction: "On schedule",
    complianceImpact: "None",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-SVC-AC700",
    lastUpdatedAt: "2026-06-09T11:00:00Z",
  },
  {
    id: "mnt-17",
    itemId: "MNT-INS-009",
    itemName: "Heat Exchanger Inspection",
    category: "Inspection",
    plantId: "TRE",
    area: "Distillation",
    assetId: "E-3012",
    assetName: "Beer Preheater / Reboiler",
    maintenanceType: "Plate pack & gasket inspection",
    status: "Due",
    criticality: "high",
    riskLevel: "high",
    dueDate: "2026-06-20",
    lastCompletedDate: "2025-12-20",
    nextScheduledDate: "2026-06-20",
    frequency: "Semi-annual",
    responsibleTeam: "Maintenance",
    owner: "Maintenance Planner",
    workOrderId: "WO-88695",
    workOrderStatus: "In progress",
    requiredParts: "Plate HX gasket set (reserved)",
    requiredPartsAvailable: true,
    storageLocation: "Warehouse A / Bin 08-D",
    estimatedDowntimeImpact: "Column slowdown during open-up",
    operationalImpact: "Distillation heat recovery efficiency",
    recommendedAction: "Complete inspection during planned window",
    complianceImpact: "None",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-INS-E3012",
    lastUpdatedAt: "2026-06-15T08:00:00Z",
  },
  {
    id: "mnt-18",
    itemId: "MNT-SAF-002",
    itemName: "Fermenter Relief Valve Inspection",
    category: "Safety",
    plantId: "PLY",
    area: "Fermentation",
    assetId: "PSV-6418",
    assetName: "Fermenter B Relief Valve",
    maintenanceType: "API 576 relief device pop test",
    status: "Overdue",
    criticality: "critical",
    riskLevel: "critical",
    dueDate: "2026-06-01",
    lastCompletedDate: "2024-06-01",
    nextScheduledDate: "2026-06-01",
    frequency: "Every 24 months",
    responsibleTeam: "Reliability",
    owner: "Brian Henderson",
    workOrderId: "WO-88860",
    workOrderStatus: "Open",
    requiredParts: "PSV rupture disc spare",
    requiredPartsAvailable: false,
    storageLocation: "Safety cage / Locker S2",
    estimatedDowntimeImpact: "Fermenter offline until restored",
    operationalImpact: "Overpressure protection for Ferm B",
    recommendedAction: "Source disc and complete pop test urgently",
    complianceImpact: "OSHA PSM / API 576 relief integrity",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-SAF-PSV6418",
    lastUpdatedAt: "2026-06-15T09:20:00Z",
  },
  {
    id: "mnt-19",
    itemId: "MNT-CAL-006",
    itemName: "Beer Flow Meter Calibration",
    category: "Calibration",
    plantId: "PLY",
    area: "Fermentation",
    assetId: "FT-6402-A",
    assetName: "Ferm A Flow Transmitter",
    maintenanceType: "Mag flow meter verification",
    status: "Compliant",
    criticality: "low",
    riskLevel: "low",
    dueDate: "2026-08-01",
    lastCompletedDate: "2026-02-01",
    nextScheduledDate: "2026-08-01",
    frequency: "Every 6 months",
    responsibleTeam: "Instrumentation",
    owner: "James Reed",
    workOrderStatus: "Closed",
    requiredParts: "None",
    requiredPartsAvailable: true,
    storageLocation: "N/A",
    estimatedDowntimeImpact: "No downtime",
    operationalImpact: "Mass balance accuracy on Ferm A",
    recommendedAction: "On schedule",
    complianceImpact: "None",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-CAL-FT6402A",
    lastUpdatedAt: "2026-06-08T09:00:00Z",
  },
  {
    id: "mnt-20",
    itemId: "MNT-SAF-003",
    itemName: "Fire Suppression System Inspection",
    category: "Safety",
    plantId: "PLY",
    area: "Plant-wide",
    assetId: "FS-SYS-01",
    assetName: "Fire Suppression & Sprinkler System",
    maintenanceType: "NFPA 25 inspection & test",
    status: "Due",
    criticality: "critical",
    riskLevel: "high",
    dueDate: "2026-06-21",
    lastCompletedDate: "2025-12-21",
    nextScheduledDate: "2026-06-21",
    frequency: "Semi-annual",
    responsibleTeam: "Safety / EHS",
    owner: "EHS Manager",
    workOrderId: "WO-89020",
    workOrderStatus: "Open",
    requiredParts: "Test connections / vendor kit",
    requiredPartsAvailable: true,
    storageLocation: "Vendor managed",
    estimatedDowntimeImpact: "None — system stays in service",
    operationalImpact: "Life-safety and asset protection",
    recommendedAction: "Schedule NFPA 25 vendor inspection",
    complianceImpact: "NFPA 25 / insurance requirement",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-SAF-FSSYS01",
    lastUpdatedAt: "2026-06-15T07:15:00Z",
  },
  {
    id: "mnt-21",
    itemId: "MNT-SAF-004",
    itemName: "Lockout/Tagout Program Inspection",
    category: "Safety",
    plantId: "PLY",
    area: "Maintenance",
    assetId: "LOTO-PROG",
    assetName: "Energy Control (LOTO) Program",
    maintenanceType: "Annual LOTO procedure audit",
    status: "Compliant",
    criticality: "medium",
    riskLevel: "medium",
    dueDate: "2026-07-15",
    lastCompletedDate: "2025-07-15",
    nextScheduledDate: "2026-07-15",
    frequency: "Annual",
    responsibleTeam: "Safety / EHS",
    owner: "EHS Manager",
    workOrderStatus: "Closed",
    requiredParts: "None",
    requiredPartsAvailable: true,
    storageLocation: "N/A",
    estimatedDowntimeImpact: "None",
    operationalImpact: "Worker safety during maintenance",
    recommendedAction: "On schedule",
    complianceImpact: "OSHA 1910.147 energy control",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-SAF-LOTO",
    lastUpdatedAt: "2026-06-07T13:00:00Z",
  },
  {
    id: "mnt-22",
    itemId: "MNT-SAF-005",
    itemName: "Confined Space Equipment Inspection",
    category: "Safety",
    plantId: "PLY",
    area: "Plant-wide",
    assetId: "CSE-KIT-01",
    assetName: "Confined Space Entry Equipment Set",
    maintenanceType: "Gas monitor + retrieval gear inspection",
    status: "Due",
    criticality: "medium",
    riskLevel: "medium",
    dueDate: "2026-06-22",
    lastCompletedDate: "2026-03-22",
    nextScheduledDate: "2026-06-22",
    frequency: "Quarterly",
    responsibleTeam: "Safety / EHS",
    owner: "EHS Manager",
    workOrderId: "WO-89022",
    workOrderStatus: "Open",
    requiredParts: "Gas monitor calibration gas",
    requiredPartsAvailable: true,
    storageLocation: "Safety equipment room",
    estimatedDowntimeImpact: "None",
    operationalImpact: "Safe entry for tank/vessel work",
    recommendedAction: "Bump-test monitors and inspect gear",
    complianceImpact: "OSHA 1910.146 confined space",
    sourceSystem: "CMMS",
    sourceRecordId: "CMMS-SAF-CSEKIT01",
    lastUpdatedAt: "2026-06-15T08:40:00Z",
  },
];

export function overdueActions(items: MaintenanceAction[]) {
  return items.filter((i) => i.status === "Overdue");
}

export function dueThisWeekActions(items: MaintenanceAction[]) {
  return items.filter((i) => {
    if (i.status === "Compliant") return false;
    const days = daysUntilDue(i.dueDate);
    return days >= 0 && days <= 7;
  });
}

export function criticalAssetRiskActions(items: MaintenanceAction[]) {
  return items.filter(
    (i) => i.riskLevel === "critical" || i.criticality === "critical",
  );
}

export function criticalOverdueActions(items: MaintenanceAction[]) {
  return items.filter(
    (i) => i.status === "Overdue" && i.criticality === "critical",
  );
}

export function partsBlockingActions(items: MaintenanceAction[]) {
  return items.filter(
    (i) => i.status !== "Compliant" && !i.requiredPartsAvailable,
  );
}

export function maintenanceActionKpis(items: MaintenanceAction[]) {
  return {
    total: items.length,
    overdue: overdueActions(items).length,
    dueThisWeek: dueThisWeekActions(items).length,
    criticalAssetRisks: criticalAssetRiskActions(items).length,
  };
}
