/** Demo fixture — Lakeview Ethanol procurement (ERP / buying workflow) */

export type ProcurementRiskLevel = "low" | "medium" | "high" | "critical";

export type PurchaseOrderStatus =
  | "not_started"
  | "requested"
  | "approved"
  | "ordered"
  | "shipped"
  | "received";

export type ProcurementCategory =
  | "Chemical"
  | "Consumable"
  | "Feedstock"
  | "Nutrient"
  | "Biological"
  | "CIP"
  | "Service";

export type ProcurementItem = {
  id: string;
  itemId: string;
  itemName: string;
  category: ProcurementCategory;
  plantId: "PLY" | "TRE";
  area: string;
  currentStock: number;
  unitOfMeasure: string;
  minimumStock: number;
  targetStock: number;
  daysOfCover: number;
  consumptionRate: number;
  consumptionUnit: string;
  leadTimeDays: number;
  requiredByDate: string;
  supplierName: string;
  lastPurchasePrice: number;
  priceUnit: string;
  estimatedCost: number;
  purchaseOrderStatus: PurchaseOrderStatus;
  purchaseOrderId?: string;
  riskLevel: ProcurementRiskLevel;
  operationalImpact: string;
  recommendedAction: string;
  owner: string;
  lastUpdatedAt: string;
  /** When a spare part overlaps maintenance domain — reference only */
  relatedWorkOrderId?: string;
};

export const PURCHASE_ORDER_LABELS: Record<PurchaseOrderStatus, string> = {
  not_started: "Not started",
  requested: "Requested",
  approved: "Approved",
  ordered: "Ordered",
  shipped: "Shipped",
  received: "Received",
};

export const LAKEVIEW_PROCUREMENT_ITEMS: ProcurementItem[] = [
  {
    id: "proc-3",
    itemId: "FEED-CORN-001",
    itemName: "Yellow #2 Corn",
    category: "Feedstock",
    plantId: "PLY",
    area: "Mash",
    currentStock: 12500,
    unitOfMeasure: "bu",
    minimumStock: 8000,
    targetStock: 20000,
    daysOfCover: 9.5,
    consumptionRate: 1315,
    consumptionUnit: "bu/day",
    leadTimeDays: 3,
    requiredByDate: "2026-06-20",
    supplierName: "Midwest Grain Co-op",
    lastPurchasePrice: 4.82,
    priceUnit: "/ bu",
    estimatedCost: 36150,
    purchaseOrderStatus: "ordered",
    purchaseOrderId: "PO-10475",
    riskLevel: "low",
    operationalImpact: "Mash throughput unaffected this week",
    recommendedAction: "Monitor railcar ETA",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T08:00:00Z",
  },
  {
    id: "proc-1",
    itemId: "CHEM-ENZ-001",
    itemName: "Alpha Amylase Enzyme",
    category: "Chemical",
    plantId: "PLY",
    area: "Fermentation",
    currentStock: 420,
    unitOfMeasure: "L",
    minimumStock: 300,
    targetStock: 900,
    daysOfCover: 4.8,
    consumptionRate: 87.5,
    consumptionUnit: "L/day",
    leadTimeDays: 7,
    requiredByDate: "2026-06-22",
    supplierName: "Preferred Supplier A",
    lastPurchasePrice: 18.4,
    priceUnit: "/ L",
    estimatedCost: 8832,
    purchaseOrderStatus: "requested",
    purchaseOrderId: "PO-10492",
    riskLevel: "high",
    operationalImpact: "Fermentation yield risk if liquefaction dosing stops",
    recommendedAction: "Expedite purchase order",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:30:00Z",
  },
  {
    id: "proc-2",
    itemId: "CHEM-GLUCO-001",
    itemName: "Gluco Amylase",
    category: "Chemical",
    plantId: "PLY",
    area: "Fermentation",
    currentStock: 310,
    unitOfMeasure: "L",
    minimumStock: 200,
    targetStock: 600,
    daysOfCover: 6.2,
    consumptionRate: 50,
    consumptionUnit: "L/day",
    leadTimeDays: 7,
    requiredByDate: "2026-06-25",
    supplierName: "Preferred Supplier A",
    lastPurchasePrice: 22.1,
    priceUnit: "/ L",
    estimatedCost: 6410,
    purchaseOrderStatus: "approved",
    purchaseOrderId: "PO-10488",
    riskLevel: "medium",
    operationalImpact: "Saccharification rate may drop",
    recommendedAction: "Confirm ship date with supplier",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:30:00Z",
  },
  {
    id: "proc-4",
    itemId: "BIO-YEAST-001",
    itemName: "Active Dry Yeast",
    category: "Biological",
    plantId: "PLY",
    area: "Fermentation",
    currentStock: 180,
    unitOfMeasure: "kg",
    minimumStock: 200,
    targetStock: 500,
    daysOfCover: 3.1,
    consumptionRate: 58,
    consumptionUnit: "kg/day",
    leadTimeDays: 5,
    requiredByDate: "2026-06-18",
    supplierName: "BioFerm Supply",
    lastPurchasePrice: 12.6,
    priceUnit: "/ kg",
    estimatedCost: 4032,
    purchaseOrderStatus: "not_started",
    riskLevel: "critical",
    operationalImpact: "Batch 6418 pitch window at risk",
    recommendedAction: "Raise emergency PO today",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:45:00Z",
  },
  {
    id: "proc-5",
    itemId: "NUT-DAP-001",
    itemName: "DAP Nutrient",
    category: "Nutrient",
    plantId: "PLY",
    area: "Fermentation",
    currentStock: 24,
    unitOfMeasure: "bags",
    minimumStock: 10,
    targetStock: 40,
    daysOfCover: 12,
    consumptionRate: 2,
    consumptionUnit: "bags/day",
    leadTimeDays: 4,
    requiredByDate: "2026-06-28",
    supplierName: "ChemServe Midwest",
    lastPurchasePrice: 48,
    priceUnit: "/ bag",
    estimatedCost: 768,
    purchaseOrderStatus: "received",
    purchaseOrderId: "PO-10460",
    riskLevel: "low",
    operationalImpact: "No immediate fermentation impact",
    recommendedAction: "Monitor consumption",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-14T16:00:00Z",
  },
  {
    id: "proc-6",
    itemId: "CIP-CAUST-001",
    itemName: "CIP Caustic 50%",
    category: "CIP",
    plantId: "PLY",
    area: "Utilities",
    currentStock: 310,
    unitOfMeasure: "gal",
    minimumStock: 150,
    targetStock: 500,
    daysOfCover: 8.4,
    consumptionRate: 37,
    consumptionUnit: "gal/day",
    leadTimeDays: 6,
    requiredByDate: "2026-06-24",
    supplierName: "ChemServe Midwest",
    lastPurchasePrice: 2.15,
    priceUnit: "/ gal",
    estimatedCost: 409,
    purchaseOrderStatus: "shipped",
    purchaseOrderId: "PO-10490",
    riskLevel: "medium",
    operationalImpact: "CIP window may slip if delivery late",
    recommendedAction: "Track inbound shipment",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T07:15:00Z",
  },
  {
    id: "proc-7",
    itemId: "SP-PUMP-SEAL-044",
    itemName: "Centrifugal Pump Mechanical Seal Kit",
    category: "Consumable",
    plantId: "TRE",
    area: "Distillation",
    currentStock: 1,
    unitOfMeasure: "kits",
    minimumStock: 2,
    targetStock: 4,
    daysOfCover: 0,
    consumptionRate: 0.25,
    consumptionUnit: "kits/month",
    leadTimeDays: 14,
    requiredByDate: "2026-06-20",
    supplierName: "Rotating Equipment Parts Co.",
    lastPurchasePrice: 1240,
    priceUnit: "/ kit",
    estimatedCost: 2480,
    purchaseOrderStatus: "ordered",
    purchaseOrderId: "PO-10495",
    riskLevel: "high",
    operationalImpact: "Beer feed pump P-4402 reliability",
    recommendedAction: "Coordinate with maintenance on WO timing",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:30:00Z",
    relatedWorkOrderId: "WO-88721",
  },
  {
    id: "proc-8",
    itemId: "SVC-CAL-INST",
    itemName: "Annual Instrument Calibration Service",
    category: "Service",
    plantId: "PLY",
    area: "Fermentation",
    currentStock: 0,
    unitOfMeasure: "contract",
    minimumStock: 1,
    targetStock: 1,
    daysOfCover: 0,
    consumptionRate: 1,
    consumptionUnit: "contract/year",
    leadTimeDays: 21,
    requiredByDate: "2026-07-01",
    supplierName: "Precision Cal Labs",
    lastPurchasePrice: 18500,
    priceUnit: "/ year",
    estimatedCost: 18500,
    purchaseOrderStatus: "requested",
    purchaseOrderId: "PO-10499",
    riskLevel: "medium",
    operationalImpact: "TT-6418-B calibration window",
    recommendedAction: "Route for approval before month end",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T06:00:00Z",
  },
  {
    id: "proc-9",
    itemId: "NUT-UREA-001",
    itemName: "Urea (Nitrogen Source)",
    category: "Nutrient",
    plantId: "PLY",
    area: "Fermentation",
    currentStock: 2.05,
    unitOfMeasure: "tons",
    minimumStock: 2,
    targetStock: 6,
    daysOfCover: 9.3,
    consumptionRate: 0.22,
    consumptionUnit: "tons/day",
    leadTimeDays: 6,
    requiredByDate: "2026-06-27",
    supplierName: "ChemServe Midwest",
    lastPurchasePrice: 540,
    priceUnit: "/ ton",
    estimatedCost: 2160,
    purchaseOrderStatus: "not_started",
    riskLevel: "medium",
    operationalImpact: "Free amino nitrogen supplementation for yeast health",
    recommendedAction: "Review usage and reorder before threshold",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T08:30:00Z",
  },
  {
    id: "proc-10",
    itemId: "CHEM-H2SO4-001",
    itemName: "Sulfuric Acid 93%",
    category: "Chemical",
    plantId: "PLY",
    area: "Mash",
    currentStock: 980,
    unitOfMeasure: "gal",
    minimumStock: 500,
    targetStock: 1500,
    daysOfCover: 11.2,
    consumptionRate: 87,
    consumptionUnit: "gal/day",
    leadTimeDays: 8,
    requiredByDate: "2026-06-29",
    supplierName: "Industrial Acids LLC",
    lastPurchasePrice: 1.85,
    priceUnit: "/ gal",
    estimatedCost: 1813,
    purchaseOrderStatus: "approved",
    purchaseOrderId: "PO-10503",
    riskLevel: "low",
    operationalImpact: "Mash pH control unaffected this cycle",
    recommendedAction: "Monitor consumption",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T07:45:00Z",
  },
  {
    id: "proc-11",
    itemId: "CHEM-ANTIFOAM-001",
    itemName: "Silicone Antifoam Emulsion",
    category: "Chemical",
    plantId: "PLY",
    area: "Fermentation",
    currentStock: 95,
    unitOfMeasure: "gal",
    minimumStock: 120,
    targetStock: 300,
    daysOfCover: 4.5,
    consumptionRate: 21,
    consumptionUnit: "gal/day",
    leadTimeDays: 7,
    requiredByDate: "2026-06-19",
    supplierName: "ChemServe Midwest",
    lastPurchasePrice: 9.4,
    priceUnit: "/ gal",
    estimatedCost: 1928,
    purchaseOrderStatus: "requested",
    purchaseOrderId: "PO-10501",
    riskLevel: "high",
    operationalImpact: "Foam-overs risk fermenter carryover and losses",
    recommendedAction: "Expedite purchase order",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:10:00Z",
  },
  {
    id: "proc-12",
    itemId: "FEED-DENAT-001",
    itemName: "Natural Gasoline Denaturant",
    category: "Feedstock",
    plantId: "PLY",
    area: "Loadout",
    currentStock: 6200,
    unitOfMeasure: "gal",
    minimumStock: 4000,
    targetStock: 12000,
    daysOfCover: 5.1,
    consumptionRate: 1215,
    consumptionUnit: "gal/day",
    leadTimeDays: 4,
    requiredByDate: "2026-06-21",
    supplierName: "Gulf Coast Fuels",
    lastPurchasePrice: 2.34,
    priceUnit: "/ gal",
    estimatedCost: 14508,
    purchaseOrderStatus: "ordered",
    purchaseOrderId: "PO-10498",
    riskLevel: "high",
    operationalImpact: "Cannot certify/ship denatured ethanol without it",
    recommendedAction: "Confirm inbound truck schedule",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T08:50:00Z",
  },
  {
    id: "proc-13",
    itemId: "CIP-CTBIO-001",
    itemName: "Cooling Tower Biocide",
    category: "CIP",
    plantId: "TRE",
    area: "Utilities",
    currentStock: 60,
    unitOfMeasure: "gal",
    minimumStock: 40,
    targetStock: 160,
    daysOfCover: 15,
    consumptionRate: 4,
    consumptionUnit: "gal/day",
    leadTimeDays: 9,
    requiredByDate: "2026-07-02",
    supplierName: "AquaTreat Solutions",
    lastPurchasePrice: 14.2,
    priceUnit: "/ gal",
    estimatedCost: 1420,
    purchaseOrderStatus: "not_started",
    riskLevel: "low",
    operationalImpact: "Microbial fouling control in cooling loop",
    recommendedAction: "Monitor consumption",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-14T15:20:00Z",
  },
  {
    id: "proc-14",
    itemId: "CHEM-BOILER-001",
    itemName: "Boiler Treatment Chemical",
    category: "Chemical",
    plantId: "TRE",
    area: "Utilities",
    currentStock: 28,
    unitOfMeasure: "gal",
    minimumStock: 30,
    targetStock: 100,
    daysOfCover: 6,
    consumptionRate: 4.6,
    consumptionUnit: "gal/day",
    leadTimeDays: 10,
    requiredByDate: "2026-06-23",
    supplierName: "AquaTreat Solutions",
    lastPurchasePrice: 17.5,
    priceUnit: "/ gal",
    estimatedCost: 1260,
    purchaseOrderStatus: "requested",
    purchaseOrderId: "PO-10505",
    riskLevel: "high",
    operationalImpact: "Boiler scale/corrosion risk affects steam supply",
    recommendedAction: "Expedite — cover shorter than lead time",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:05:00Z",
  },
  {
    id: "proc-15",
    itemId: "LAB-REAGENT-001",
    itemName: "Enzyme Activity Assay Reagent Kit",
    category: "Consumable",
    plantId: "PLY",
    area: "Lab",
    currentStock: 14,
    unitOfMeasure: "kits",
    minimumStock: 6,
    targetStock: 24,
    daysOfCover: 28,
    consumptionRate: 0.5,
    consumptionUnit: "kits/day",
    leadTimeDays: 12,
    requiredByDate: "2026-07-05",
    supplierName: "LabChem Distributors",
    lastPurchasePrice: 320,
    priceUnit: "/ kit",
    estimatedCost: 3200,
    purchaseOrderStatus: "received",
    purchaseOrderId: "PO-10470",
    riskLevel: "low",
    operationalImpact: "QA enzyme verification cadence",
    recommendedAction: "Monitor consumption",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-13T11:00:00Z",
  },
  {
    id: "proc-16",
    itemId: "CIP-DESCALE-001",
    itemName: "Acid Descaler (Evaporator CIP)",
    category: "CIP",
    plantId: "PLY",
    area: "Evaporation",
    currentStock: 210,
    unitOfMeasure: "gal",
    minimumStock: 200,
    targetStock: 600,
    daysOfCover: 7,
    consumptionRate: 30,
    consumptionUnit: "gal/day",
    leadTimeDays: 6,
    requiredByDate: "2026-06-24",
    supplierName: "ChemServe Midwest",
    lastPurchasePrice: 3.1,
    priceUnit: "/ gal",
    estimatedCost: 1209,
    purchaseOrderStatus: "not_started",
    riskLevel: "medium",
    operationalImpact: "Evaporator scaling reduces heat-transfer efficiency",
    recommendedAction: "Reorder near threshold",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T07:30:00Z",
  },
  {
    id: "proc-17",
    itemId: "SP-SIEVE-MED-001",
    itemName: "Molecular Sieve Beads (3A)",
    category: "Consumable",
    plantId: "TRE",
    area: "Dehydration",
    currentStock: 0.5,
    unitOfMeasure: "tons",
    minimumStock: 1,
    targetStock: 3,
    daysOfCover: 0,
    consumptionRate: 0.02,
    consumptionUnit: "tons/day",
    leadTimeDays: 21,
    requiredByDate: "2026-06-30",
    supplierName: "Molecular Sieve Tech",
    lastPurchasePrice: 5200,
    priceUnit: "/ ton",
    estimatedCost: 13000,
    purchaseOrderStatus: "ordered",
    purchaseOrderId: "PO-10496",
    riskLevel: "critical",
    operationalImpact: "200-proof dehydration capacity at risk on bed change",
    recommendedAction: "Expedite — 21-day lead, cover exhausted",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:40:00Z",
  },
  {
    id: "proc-18",
    itemId: "PKG-LOADOUT-001",
    itemName: "Rail Seals, Placards & Loadout Supplies",
    category: "Consumable",
    plantId: "PLY",
    area: "Loadout",
    currentStock: 320,
    unitOfMeasure: "pieces",
    minimumStock: 150,
    targetStock: 800,
    daysOfCover: 16,
    consumptionRate: 20,
    consumptionUnit: "pieces/day",
    leadTimeDays: 5,
    requiredByDate: "2026-07-03",
    supplierName: "RailShip Supply Co.",
    lastPurchasePrice: 6.5,
    priceUnit: "/ piece",
    estimatedCost: 2080,
    purchaseOrderStatus: "shipped",
    purchaseOrderId: "PO-10493",
    riskLevel: "low",
    operationalImpact: "Shipment documentation/compliance for railcars",
    recommendedAction: "Track inbound shipment",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T06:40:00Z",
  },
  {
    id: "proc-19",
    itemId: "PPE-SAFETY-001",
    itemName: "PPE Consumables (Gloves & Cartridges)",
    category: "Consumable",
    plantId: "PLY",
    area: "Maintenance",
    currentStock: 145,
    unitOfMeasure: "boxes",
    minimumStock: 150,
    targetStock: 400,
    daysOfCover: 18,
    consumptionRate: 8,
    consumptionUnit: "boxes/day",
    leadTimeDays: 6,
    requiredByDate: "2026-07-01",
    supplierName: "SafetyFirst Industrial",
    lastPurchasePrice: 22,
    priceUnit: "/ box",
    estimatedCost: 3300,
    purchaseOrderStatus: "not_started",
    riskLevel: "medium",
    operationalImpact: "Safety compliance for plant personnel",
    recommendedAction: "Reorder — below minimum",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T08:15:00Z",
  },
  {
    id: "proc-20",
    itemId: "CHEM-ANTISCAL-001",
    itemName: "RO Antiscalant (Water Treatment)",
    category: "Chemical",
    plantId: "TRE",
    area: "Water Treatment",
    currentStock: 410,
    unitOfMeasure: "gal",
    minimumStock: 150,
    targetStock: 500,
    daysOfCover: 22,
    consumptionRate: 18,
    consumptionUnit: "gal/day",
    leadTimeDays: 7,
    requiredByDate: "2026-07-08",
    supplierName: "AquaTreat Solutions",
    lastPurchasePrice: 8.8,
    priceUnit: "/ gal",
    estimatedCost: 3608,
    purchaseOrderStatus: "received",
    purchaseOrderId: "PO-10462",
    riskLevel: "low",
    operationalImpact: "RO membrane scaling protection",
    recommendedAction: "Monitor consumption",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-12T14:00:00Z",
  },
  {
    id: "proc-21",
    itemId: "SP-CARBON-MED-001",
    itemName: "Activated Carbon Filter Media",
    category: "Consumable",
    plantId: "PLY",
    area: "Utilities",
    currentStock: 1.02,
    unitOfMeasure: "tons",
    minimumStock: 1,
    targetStock: 4,
    daysOfCover: 20,
    consumptionRate: 0.05,
    consumptionUnit: "tons/day",
    leadTimeDays: 14,
    requiredByDate: "2026-07-04",
    supplierName: "FilterMedia Industrial",
    lastPurchasePrice: 3100,
    priceUnit: "/ ton",
    estimatedCost: 9300,
    purchaseOrderStatus: "not_started",
    riskLevel: "medium",
    operationalImpact: "Process water polishing capacity",
    recommendedAction: "Plan reorder against 14-day lead time",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T07:55:00Z",
  },
  {
    id: "proc-22",
    itemId: "CHEM-LIME-001",
    itemName: "Hydrated Lime (pH Adjust)",
    category: "Chemical",
    plantId: "TRE",
    area: "Water Treatment",
    currentStock: 3.1,
    unitOfMeasure: "tons",
    minimumStock: 3,
    targetStock: 10,
    daysOfCover: 8,
    consumptionRate: 0.38,
    consumptionUnit: "tons/day",
    leadTimeDays: 5,
    requiredByDate: "2026-06-26",
    supplierName: "Midwest Minerals",
    lastPurchasePrice: 230,
    priceUnit: "/ ton",
    estimatedCost: 1610,
    purchaseOrderStatus: "approved",
    purchaseOrderId: "PO-10504",
    riskLevel: "medium",
    operationalImpact: "Effluent pH neutralization compliance",
    recommendedAction: "Reorder near threshold",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T08:05:00Z",
  },
  {
    id: "proc-23",
    itemId: "CHEM-EMULBRK-001",
    itemName: "Emulsion Breaker (Corn Oil Recovery)",
    category: "Chemical",
    plantId: "PLY",
    area: "Oil Recovery",
    currentStock: 70,
    unitOfMeasure: "gal",
    minimumStock: 100,
    targetStock: 300,
    daysOfCover: 3.6,
    consumptionRate: 19,
    consumptionUnit: "gal/day",
    leadTimeDays: 7,
    requiredByDate: "2026-06-20",
    supplierName: "ChemServe Midwest",
    lastPurchasePrice: 11.9,
    priceUnit: "/ gal",
    estimatedCost: 2737,
    purchaseOrderStatus: "requested",
    purchaseOrderId: "PO-10502",
    riskLevel: "high",
    operationalImpact: "Distillers corn oil yield (co-product revenue) at risk",
    recommendedAction: "Expedite — protects co-product margin",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:20:00Z",
  },
  {
    id: "proc-24",
    itemId: "BIO-ANTIMIC-001",
    itemName: "Fermentation Antimicrobial (Virginiamycin)",
    category: "Biological",
    plantId: "PLY",
    area: "Fermentation",
    currentStock: 18,
    unitOfMeasure: "kg",
    minimumStock: 25,
    targetStock: 80,
    daysOfCover: 2.4,
    consumptionRate: 7.5,
    consumptionUnit: "kg/day",
    leadTimeDays: 10,
    requiredByDate: "2026-06-18",
    supplierName: "BioFerm Supply",
    lastPurchasePrice: 96,
    priceUnit: "/ kg",
    estimatedCost: 5952,
    purchaseOrderStatus: "not_started",
    riskLevel: "critical",
    operationalImpact: "Lactobacillus contamination risk lowers ethanol yield",
    recommendedAction: "Raise emergency PO today",
    owner: "Procurement",
    lastUpdatedAt: "2026-06-15T09:50:00Z",
  },
];

export function procurementKpis(items: ProcurementItem[]) {
  return {
    total: items.length,
    criticalRisks: items.filter(
      (i) => i.riskLevel === "critical" || i.riskLevel === "high",
    ).length,
    belowMinimum: items.filter((i) => i.currentStock <= i.minimumStock).length,
    stockoutBeforeLead: items.filter(
      (i) => i.daysOfCover < i.leadTimeDays,
    ).length,
    openPos: items.filter(
      (i) =>
        i.purchaseOrderStatus !== "received" &&
        i.purchaseOrderStatus !== "not_started",
    ).length,
    supplierIssues: items.filter(
      (i) => i.leadTimeDays >= 14 && i.daysOfCover < i.leadTimeDays,
    ).length,
  };
}

/** Within 5% above the minimum threshold but not yet below it — early warning */
export const NEAR_MINIMUM_FACTOR = 1.05;

export function nearMinimumStock(items: ProcurementItem[]) {
  return items.filter(
    (i) =>
      i.currentStock > i.minimumStock &&
      i.currentStock <= i.minimumStock * NEAR_MINIMUM_FACTOR,
  );
}

export function criticalPurchaseRisks(items: ProcurementItem[]) {
  return items.filter(
    (i) => i.riskLevel === "critical" || i.riskLevel === "high",
  );
}

export function itemsBelowMinimum(items: ProcurementItem[]) {
  return items.filter((i) => i.currentStock <= i.minimumStock);
}

export function stockoutBeforeLeadTime(items: ProcurementItem[]) {
  return items.filter((i) => i.daysOfCover < i.leadTimeDays);
}

export function openPurchaseOrders(items: ProcurementItem[]) {
  return items.filter(
    (i) =>
      i.purchaseOrderStatus !== "received" &&
      i.purchaseOrderStatus !== "not_started",
  );
}

export function supplierLeadTimeIssues(items: ProcurementItem[]) {
  return items.filter(
    (i) => i.leadTimeDays >= 14 && i.daysOfCover < i.leadTimeDays,
  );
}
